name = "Renice Squared"
author = "Wechirok"
version = "2.1.0-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2de6f807d4d990cec9b7bb5124bcd581ee4baa267616372b5c22710bb5c29431"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
