name = "Renice Squared"
author = "Wechirok"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f6e0ab042120f2557f56eacf9b6ffff41d81a18085f1585c6abaab2ef3e6bb52"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
