name = "Renice Squared"
author = "Wechirok"
version = "1.1.1-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b4e5a925a7b6c42e217f4092cf3840c80af48415ca4b2c0b0d9840de73406449"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
