name = "Renice Squared"
author = "Wechirok"
version = "1.1.0-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2cf90cd7208f9547ede3fe8d7c08e646c5ba4167f8cdac75c6cf1e8b03eb3221"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
