name = "Renice Squared"
author = "Wechirok"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fb8890f1045d474a1318912fdd1b822c2bf0262f0d2078f55e85e24e5d835a83"

[versions]
fabric = "0.19.5"
minecraft = "26.1.2"
